// Minimal Firebase options to satisfy analyzer during development.
// Replace these values with the ones generated by `flutterfire configure`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => const FirebaseOptions(
     apiKey: "AIzaSyBo4Ourmg3uZ1ZOD7Ns2od8jajSBrVWhCU",
  authDomain: "sensink-appdev.firebaseapp.com",
  projectId: "sensink-appdev",
  storageBucket: "sensink-appdev.firebasestorage.app",
  messagingSenderId: "837308570802",
  appId: "1:837308570802:web:8e2307ef8bdf101d88bdab",
  measurementId: "G-92Y8KM1FJT"
  );
}
